---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.21
  labels:
    derrick.service: demoboot
  name: demoboot
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    derrick.service: demoboot
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.21
  labels:
    derrick.service: demoboot
  name: demoboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: demoboot
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/jingshan/demoboot:latest
        name: web
        ports:
        - containerPort: 8080